//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolDefinition", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
    [System.SerializableAttribute()]
    public partial class VolDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BanquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LigneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Banques {
            get {
                return this.BanquesField;
            }
            set {
                if ((object.ReferenceEquals(this.BanquesField, value) != true)) {
                    this.BanquesField = value;
                    this.RaisePropertyChanged("Banques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIE {
            get {
                return this.CIEField;
            }
            set {
                if ((object.ReferenceEquals(this.CIEField, value) != true)) {
                    this.CIEField = value;
                    this.RaisePropertyChanged("CIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ligne {
            get {
                return this.LigneField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneField, value) != true)) {
                    this.LigneField = value;
                    this.RaisePropertyChanged("Ligne");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BagageDefinition", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
    [System.SerializableAttribute()]
    public partial class BagageDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodeIATAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdVolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrioritaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodeIATA {
            get {
                return this.CodeIATAField;
            }
            set {
                if ((this.CodeIATAField.Equals(value) != true)) {
                    this.CodeIATAField = value;
                    this.RaisePropertyChanged("CodeIATA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation {
            get {
                return this.DateCreationField;
            }
            set {
                if ((this.DateCreationField.Equals(value) != true)) {
                    this.DateCreationField = value;
                    this.RaisePropertyChanged("DateCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdVol {
            get {
                return this.IdVolField;
            }
            set {
                if ((this.IdVolField.Equals(value) != true)) {
                    this.IdVolField = value;
                    this.RaisePropertyChanged("IdVol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Prioritary {
            get {
                return this.PrioritaryField;
            }
            set {
                if ((this.PrioritaryField.Equals(value) != true)) {
                    this.PrioritaryField = value;
                    this.RaisePropertyChanged("Prioritary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultipleBaggageException", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
    [System.SerializableAttribute()]
    public partial class MultipleBaggageException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference2.BagageDefinition[] BaggagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference2.BagageDefinition[] Baggages {
            get {
                return this.BaggagesField;
            }
            set {
                if ((object.ReferenceEquals(this.BaggagesField, value) != true)) {
                    this.BaggagesField = value;
                    this.RaisePropertyChanged("Baggages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersoFaultException", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
    [System.SerializableAttribute()]
    public partial class PersoFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int V1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int V2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int V1 {
            get {
                return this.V1Field;
            }
            set {
                if ((this.V1Field.Equals(value) != true)) {
                    this.V1Field = value;
                    this.RaisePropertyChanged("V1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int V2 {
            get {
                return this.V2Field;
            }
            set {
                if ((this.V2Field.Equals(value) != true)) {
                    this.V2Field = value;
                    this.RaisePropertyChanged("V2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IMyAirportService")]
    public interface IMyAirportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/DetailVol2", ReplyAction="http://tempuri.org/IMyAirportService/DetailVol2Response")]
        Client.ServiceReference2.VolDefinition DetailVol2(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/DetailVol2", ReplyAction="http://tempuri.org/IMyAirportService/DetailVol2Response")]
        System.Threading.Tasks.Task<Client.ServiceReference2.VolDefinition> DetailVol2Async(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/RechercherBagagesParIata", ReplyAction="http://tempuri.org/IMyAirportService/RechercherBagagesParIataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference2.MultipleBaggageException), Action="http://tempuri.org/IMyAirportService/RechercherBagagesParIataMultipleBaggageExcep" +
            "tionFault", Name="MultipleBaggageException", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
        Client.ServiceReference2.BagageDefinition RechercherBagagesParIata(string iata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/RechercherBagagesParIata", ReplyAction="http://tempuri.org/IMyAirportService/RechercherBagagesParIataResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference2.BagageDefinition> RechercherBagagesParIataAsync(string iata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/CreerBaggage", ReplyAction="http://tempuri.org/IMyAirportService/CreerBaggageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference2.PersoFaultException), Action="http://tempuri.org/IMyAirportService/CreerBaggagePersoFaultExceptionFault", Name="PersoFaultException", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Entities")]
        int CreerBaggage(Client.ServiceReference2.BagageDefinition baggage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAirportService/CreerBaggage", ReplyAction="http://tempuri.org/IMyAirportService/CreerBaggageResponse")]
        System.Threading.Tasks.Task<int> CreerBaggageAsync(Client.ServiceReference2.BagageDefinition baggage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyAirportServiceChannel : Client.ServiceReference2.IMyAirportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyAirportServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference2.IMyAirportService>, Client.ServiceReference2.IMyAirportService {
        
        public MyAirportServiceClient() {
        }
        
        public MyAirportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyAirportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAirportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAirportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference2.VolDefinition DetailVol2(int id) {
            return base.Channel.DetailVol2(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference2.VolDefinition> DetailVol2Async(int id) {
            return base.Channel.DetailVol2Async(id);
        }
        
        public Client.ServiceReference2.BagageDefinition RechercherBagagesParIata(string iata) {
            return base.Channel.RechercherBagagesParIata(iata);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference2.BagageDefinition> RechercherBagagesParIataAsync(string iata) {
            return base.Channel.RechercherBagagesParIataAsync(iata);
        }
        
        public int CreerBaggage(Client.ServiceReference2.BagageDefinition baggage) {
            return base.Channel.CreerBaggage(baggage);
        }
        
        public System.Threading.Tasks.Task<int> CreerBaggageAsync(Client.ServiceReference2.BagageDefinition baggage) {
            return base.Channel.CreerBaggageAsync(baggage);
        }
    }
}
