//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROPORT
    {
        public int ID_AEROPORT { get; set; }
        public string CODE_IATA { get; set; }
        public string NOM { get; set; }
        public bool LONG_COURRIER { get; set; }
    }
}
