//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOC_CS_CLA
    {
        public int ID_MOD_CLA { get; set; }
        public int ID_CRI_SELECTION { get; set; }
        public short ORDRE_TEMPOREL { get; set; }
    
        public virtual CRI_SELECTION CRI_SELECTION { get; set; }
        public virtual MODEL_CLASSEMENT MODEL_CLASSEMENT { get; set; }
    }
}
