//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAGAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAGAGE()
        {
            this.BAGAGE_VOL_APPORT = new HashSet<BAGAGE_VOL_APPORT>();
            this.BAGAGE_VOL_CNT = new HashSet<BAGAGE_VOL_CNT>();
            this.BAGAGE_OCCURENCE = new HashSet<BAGAGE_OCCURENCE>();
            this.BAGAGE_PARTICULARITE = new HashSet<BAGAGE_PARTICULARITE>();
        }
    
        public int ID_BAGAGE { get; set; }
        public Nullable<int> ID_VOL { get; set; }
        public string CODE_IATA { get; set; }
        public string ORIGINE_CREATION { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public string CLASSE { get; set; }
        public Nullable<bool> PRIORITAIRE { get; set; }
        public string STA { get; set; }
        public string LOCAL_TRANFERT { get; set; }
        public string NSUR { get; set; }
        public string SSUR { get; set; }
        public Nullable<bool> ISUR { get; set; }
        public string TSUR { get; set; }
        public string GSUR { get; set; }
        public string CSUR { get; set; }
        public string DESTINATION { get; set; }
        public string ESCALE { get; set; }
        public Nullable<bool> EMB { get; set; }
        public Nullable<bool> RECOLE { get; set; }
        public string COMPAGNIE { get; set; }
        public string LIGNE { get; set; }
        public short JOUR_EXPLOITATION { get; set; }
        public string CONTINUATION { get; set; }
        public string STATUT_EJECTION { get; set; }
        public Nullable<int> STATUT_TEMPOREL { get; set; }
        public string DCS_EMETTEUR { get; set; }
        public bool ORIGINE_SAFIR { get; set; }
        public bool EN_CONTINUATION { get; set; }
        public bool EN_TRANSFERT { get; set; }
    
        public virtual VOL VOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGAGE_VOL_APPORT> BAGAGE_VOL_APPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGAGE_VOL_CNT> BAGAGE_VOL_CNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGAGE_OCCURENCE> BAGAGE_OCCURENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGAGE_PARTICULARITE> BAGAGE_PARTICULARITE { get; set; }
    }
}
