//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAGAGE_VOL_APPORT
    {
        public string COMPAGNIE { get; set; }
        public int ID_BAGAGE { get; set; }
        public short JOUR_EXPLOITATION { get; set; }
        public string LIGNE { get; set; }
        public string AEROPORT { get; set; }
    
        public virtual BAGAGE BAGAGE { get; set; }
    }
}
