//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAGAGE_OCCURENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAGAGE_OCCURENCE()
        {
            this.BAGAGE_TRACE = new HashSet<BAGAGE_TRACE>();
        }
    
        public int ID_OCCURENCE { get; set; }
        public Nullable<int> ID_BAGAGE { get; set; }
        public string CODE_IATA { get; set; }
        public Nullable<System.DateTime> HORODATE_ENTREE_TRI { get; set; }
        public Nullable<int> DESTINATION1 { get; set; }
        public Nullable<int> DESTINATION4 { get; set; }
        public string STATUT_EJEC { get; set; }
        public string INDIC_SECTOR { get; set; }
        public int NUMERO_OCCURENCE { get; set; }
        public string COMPAGNIE { get; set; }
        public string LIGNE { get; set; }
        public string JOUR_EXPLOITATION { get; set; }
        public string ENCOURS { get; set; }
        public Nullable<int> DIRECTIONENCOURS { get; set; }
        public Nullable<int> STATUT_SURETE_EJECTION { get; set; }
        public string TYPE_TACHE { get; set; }
        public Nullable<int> ID_TACHE { get; set; }
        public Nullable<int> DERNIERE_LOC_CONNUE { get; set; }
    
        public virtual BAGAGE BAGAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGAGE_TRACE> BAGAGE_TRACE { get; set; }
    }
}
