//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPAGNIE_CLASSE
    {
        public int ID_COMPAGNIE_CLASSE { get; set; }
        public int ID_COMPAGNIE { get; set; }
        public string CLASSE { get; set; }
        public bool PRIORITAIRE { get; set; }
    
        public virtual COMPAGNIE COMPAGNIE { get; set; }
    }
}
