//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPAGNIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPAGNIE()
        {
            this.COMPAGNIE_CLASSE = new HashSet<COMPAGNIE_CLASSE>();
            this.VOLs = new HashSet<VOL>();
            this.VOLs1 = new HashSet<VOL>();
        }
    
        public int ID_COMPAGNIE { get; set; }
        public string CODE_IATA { get; set; }
        public string NUMERO_ASSISTANT { get; set; }
        public string CODE_OACI { get; set; }
        public string NOM { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<System.DateTime> DATE_OBSOLETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPAGNIE_CLASSE> COMPAGNIE_CLASSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOL> VOLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOL> VOLs1 { get; set; }
    }
}
