//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRI_SELECTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRI_SELECTION()
        {
            this.ASSOC_CS_CLA = new HashSet<ASSOC_CS_CLA>();
        }
    
        public int ID_CRI_SELECTION { get; set; }
        public Nullable<int> ID_MOD_CHR { get; set; }
        public Nullable<int> ID_MOD_SATISFACT { get; set; }
        public string TYPE_MODELE { get; set; }
        public string EXPRESSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOC_CS_CLA> ASSOC_CS_CLA { get; set; }
        public virtual MODEL_CHRONOGRAMME MODEL_CHRONOGRAMME { get; set; }
        public virtual MODEL_SATISFACTION MODEL_SATISFACTION { get; set; }
    }
}
