//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPORT()
        {
            this.ASSOC_EMP_CLA = new HashSet<ASSOC_EMP_CLA>();
            this.TACHE_GRP_BAGS = new HashSet<TACHE_GRP_BAGS>();
            this.VOL_DEPART = new HashSet<VOL_DEPART>();
        }
    
        public int ID_EMPORT { get; set; }
        public Nullable<int> ID_CHRONOGRAMME { get; set; }
        public Nullable<short> NB_BAG_CALCULE { get; set; }
        public Nullable<System.DateTime> D_ANT { get; set; }
        public Nullable<System.DateTime> D_TPS { get; set; }
        public Nullable<System.DateTime> D_DER { get; set; }
        public Nullable<System.DateTime> D_RAT { get; set; }
        public Nullable<System.DateTime> F_RAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOC_EMP_CLA> ASSOC_EMP_CLA { get; set; }
        public virtual MODEL_CHRONOGRAMME MODEL_CHRONOGRAMME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACHE_GRP_BAGS> TACHE_GRP_BAGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOL_DEPART> VOL_DEPART { get; set; }
    }
}
