//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_SATISFACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODEL_SATISFACTION()
        {
            this.CRI_SELECTION = new HashSet<CRI_SELECTION>();
            this.TACHE_GRP_BAGS = new HashSet<TACHE_GRP_BAGS>();
        }
    
        public int ID_SATISFACTION { get; set; }
        public string LIBELLE { get; set; }
        public bool OBSOLETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRI_SELECTION> CRI_SELECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACHE_GRP_BAGS> TACHE_GRP_BAGS { get; set; }
    }
}
