//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_CLASSEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODEL_CLASSEMENT()
        {
            this.ASSOC_CS_CLA = new HashSet<ASSOC_CS_CLA>();
            this.ASSOC_EMP_CLA = new HashSet<ASSOC_EMP_CLA>();
        }
    
        public int ID_CLASSEMENT { get; set; }
        public string LIBELLE { get; set; }
        public string EXPRESSION { get; set; }
        public bool OBSOLETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOC_CS_CLA> ASSOC_CS_CLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOC_EMP_CLA> ASSOC_EMP_CLA { get; set; }
    }
}
