//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARK_AVION
    {
        public int ID_PARKING { get; set; }
        public string CODE_PARKING { get; set; }
        public string ID_SARIA_PARKING { get; set; }
    }
}
