//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESSOURCE
    {
        public int ID_RESSOURCE { get; set; }
        public int ID_GROUP_TRI { get; set; }
        public int ID_RESSOURCE_GROUP { get; set; }
        public int ID_LOCALISATION { get; set; }
        public string NOM { get; set; }
        public string CODE { get; set; }
    }
}
