//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESSOURCE_GROUP
    {
        public int ID_GROUP { get; set; }
        public string NOM_GROUP { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<int> ID_TYPE_RESSOURCE { get; set; }
    }
}
