//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHE_ENTREE_TRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TACHE_ENTREE_TRI()
        {
            this.TACHE_ENTREE_TRI1 = new HashSet<TACHE_ENTREE_TRI>();
        }
    
        public int ID_TACHE { get; set; }
        public int ID_RES { get; set; }
        public Nullable<int> ID_RES_IN { get; set; }
        public System.DateTime TDEB { get; set; }
        public System.DateTime TFIN { get; set; }
        public string NIV_ALA { get; set; }
        public Nullable<short> COD_ALA { get; set; }
        public string CAR_CLASS { get; set; }
        public Nullable<int> ID_TACHE_MERE { get; set; }
        public Nullable<int> NB_BAGS_EN_COURS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACHE_ENTREE_TRI> TACHE_ENTREE_TRI1 { get; set; }
        public virtual TACHE_ENTREE_TRI TACHE_ENTREE_TRI2 { get; set; }
    }
}
