//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHE_GRP_BAGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TACHE_GRP_BAGS()
        {
            this.TACHE_GRP_BAGS1 = new HashSet<TACHE_GRP_BAGS>();
        }
    
        public int ID_TACHE { get; set; }
        public int ID_EMPORT { get; set; }
        public Nullable<int> ID_MOD_SATISFACT { get; set; }
        public Nullable<int> ID_RES { get; set; }
        public string STATUT_TEMPOREL { get; set; }
        public System.DateTime TDEB { get; set; }
        public System.DateTime TFIN { get; set; }
        public string NIV_ALA { get; set; }
        public Nullable<short> COD_ALA { get; set; }
        public string CAR_CLASS { get; set; }
        public Nullable<int> ID_TACHE_MERE { get; set; }
        public Nullable<int> NB_BAGS_EN_COURS { get; set; }
        public Nullable<int> NB_CONTAINERS { get; set; }
    
        public virtual EMPORT EMPORT { get; set; }
        public virtual MODEL_SATISFACTION MODEL_SATISFACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACHE_GRP_BAGS> TACHE_GRP_BAGS1 { get; set; }
        public virtual TACHE_GRP_BAGS TACHE_GRP_BAGS2 { get; set; }
    }
}
