//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOL_ENRGT_SUR
    {
        public int ID_RES { get; set; }
        public int ID_VOL { get; set; }
        public Nullable<System.DateTime> DEBUT { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
    
        public virtual VOL_ENRGT_SUR VOL_ENRGT_SUR1 { get; set; }
        public virtual VOL_ENRGT_SUR VOL_ENRGT_SUR2 { get; set; }
    }
}
