//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirport.Data.ModelEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOL_TYP_AVION
    {
        public int ID_TYP_AVION { get; set; }
        public string TYP { get; set; }
        public string LIB { get; set; }
        public Nullable<int> PAX_STD { get; set; }
        public Nullable<short> PAX_MAX { get; set; }
        public string OBS { get; set; }
    }
}
